
language: php
addons:
  apt:
    packages:
      - oracle-java8-set-default
  postgresql: "9.4"

notifications:
  email:
    recipients:
    - mattp@catalyst-au.net

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0
env:
 global:
   - TEST_SEARCH_ELASTIC_HOSTNAME=http://127.0.0.1
   - TEST_SEARCH_ELASTIC_PORT=9200
   - TEST_SEARCH_ELASTIC_INDEX=moodle_test
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE ESVER=2.3.4 ESURL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.4/elasticsearch-2.3.4.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE ESVER=2.4.4 ESURL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.4/elasticsearch-2.4.4.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE ESVER=5.1.2 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE ESVER=2.3.4 ESURL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.4/elasticsearch-2.3.4.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE ESVER=2.4.4 ESURL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.4/elasticsearch-2.4.4.deb
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE ESVER=5.1.2 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.deb
  - DB=pgsql MOODLE_BRANCH=master ESVER=2.3.4 ESURL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.4/elasticsearch-2.3.4.deb
  - DB=pgsql MOODLE_BRANCH=master ESVER=2.4.4 ESURL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.4/elasticsearch-2.4.4.deb
  - DB=pgsql MOODLE_BRANCH=master ESVER=5.1.2 ESURL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.deb

before_install:
  - curl -O ${ESURL} && sudo dpkg -i --force-confnew elasticsearch-${ESVER}.deb && sudo service elasticsearch restart
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin catalyst/moodle-local_aws
  - moodle-plugin-ci install -vvv
  - if [ "$MOODLE_BRANCH" == "MOODLE_31_STABLE" ]; then (cd moodle; composer require --dev --no-interaction --prefer-dist guzzlehttp/guzzle:~6.0 fabpot/goutte:~3); fi

before_script:
  - sleep 10

script:
  - moodle-plugin-ci phplint
#  - moodle-plugin-ci phpcpd
# - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci shifter
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat      # No tests yet

